"use client";

import type { NodeProps } from "@xyflow/react";
import NodeFrame, { NodeField } from "./NodeFrame";
import type { WorkspaceNode } from "./types";

function update(data: WorkspaceNode["data"], patch: Record<string, unknown>) {
  data.onChange?.(patch);
}

function ControlNode({ data, kind }: { data: WorkspaceNode["data"]; kind: "review" | "chat" | "split" | "merge" | "context" | "plugin" }) {
  if (kind === "review") return <NodeFrame title="Human Review" subtitle="Durable approval pause" accent="node-review"><NodeField label="Review prompt"><textarea className="nodrag" rows={3} value={String(data.prompt ?? "Review this step before it continues.")} onChange={(event) => update(data, { prompt: event.target.value })} /></NodeField><small>Shows inherited context, arguments, impact, and decision controls in the Run Inspector.</small></NodeFrame>;
  if (kind === "chat") return <NodeFrame title="Chat Input" subtitle="Wait for human context" accent="node-chat"><NodeField label="Question"><textarea className="nodrag" rows={3} value={String(data.prompt ?? "What should this workflow know before continuing?")} onChange={(event) => update(data, { prompt: event.target.value })} /></NodeField><small>Chat input adds context; it does not imply approval.</small></NodeFrame>;
  if (kind === "split") return <NodeFrame title="Split / Router" subtitle="Fan out or chunk input" accent="node-split"><NodeField label="Strategy"><select className="nodrag" value={String(data.chunk_strategy ?? "paragraphs")} onChange={(event) => update(data, { chunk_strategy: event.target.value })}><option value="paragraphs">Paragraphs</option><option value="lines">Lines</option><option value="characters">Characters</option><option value="tokens">Estimated tokens</option><option value="json_items">JSON items</option></select></NodeField><NodeField label="Branch mode"><select className="nodrag" value={String(data.branch_mode ?? "parallel")} onChange={(event) => update(data, { branch_mode: event.target.value })}><option value="parallel">Parallel</option><option value="sequential">Sequential</option><option value="conditional">Conditional</option><option value="chunked">Chunked map</option></select></NodeField><NodeField label="Chunk size"><input className="nodrag" type="number" min={1} max={50000} value={Number(data.chunk_size ?? 2000)} onChange={(event) => update(data, { chunk_size: Number(event.target.value) })} /></NodeField><NodeField label="Overlap"><input className="nodrag" type="number" min={0} max={49999} value={Number(data.chunk_overlap ?? 0)} onChange={(event) => update(data, { chunk_overlap: Number(event.target.value) })} /></NodeField><NodeField label="Maximum chunks"><input className="nodrag" type="number" min={1} max={256} value={Number(data.max_chunks ?? 64)} onChange={(event) => update(data, { max_chunks: Number(event.target.value) })} /></NodeField></NodeFrame>;
  if (kind === "merge") return <NodeFrame title="Merge" subtitle="Join branch/chunk outputs" accent="node-merge"><NodeField label="Merge strategy"><select className="nodrag" value={String(data.merge_strategy ?? "concatenate")} onChange={(event) => update(data, { merge_strategy: event.target.value })}><option value="concatenate">Ordered concatenate</option><option value="labeled_object">Labeled object</option><option value="json_array">JSON array</option><option value="first_success">First success</option><option value="model_reduce">Model reduce</option></select></NodeField><NodeField label="Separator"><input className="nodrag" value={String(data.separator ?? "\n\n")} onChange={(event) => update(data, { separator: event.target.value })} /></NodeField></NodeFrame>;
  if (kind === "context") return <NodeFrame title="Context" subtitle="Select inherited data" accent="node-context"><NodeField label="JSON path"><input className="nodrag" placeholder="result.items.0" value={String(data.selector ?? "")} onChange={(event) => update(data, { selector: event.target.value })} /></NodeField><small>Leave blank to pass the full context through.</small></NodeFrame>;
  return <NodeFrame title="Plugin" subtitle="Registered local extension" accent="node-plugin"><NodeField label="Plugin"><select className="nodrag" value={String(data.plugin_id ?? "run_annotation")} onChange={(event) => update(data, { plugin_id: event.target.value })}><option value="run_annotation">Run annotation</option><option value="context_selector">Context selector</option></select></NodeField><NodeField label="Configuration"><textarea className="nodrag" rows={3} value={String(data.note ?? "")} onChange={(event) => update(data, { note: event.target.value })} /></NodeField><small>Only registered handlers appear here; plugins cannot bypass approvals.</small></NodeFrame>;
}

export function ReviewNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="review" />; }
export function ChatInputNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="chat" />; }
export function SplitNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="split" />; }
export function MergeNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="merge" />; }
export function ContextNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="context" />; }
export function PluginNode({ data }: NodeProps<WorkspaceNode>) { return <ControlNode data={data} kind="plugin" />; }
